# Generated by Django 4.1.2 on 2022-10-26 16:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("TwitterApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="twitterapp",
            name="dateCreated",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="twitterapp",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
