# Generated by Django 4.1.2 on 2022-10-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TwitterApp", "0002_alter_twitterapp_datecreated_alter_twitterapp_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="twitterapp",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
