# Generated by Django 3.2 on 2022-10-28 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TwitterApp', '0003_alter_twitterapp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitterapp',
            name='tweet',
            field=models.CharField(max_length=50),
        ),
    ]
